#!/usr/bin/env bash
#this script groups the parsed Apache log data by IP and HTTP status code, count the number of occurrences
awk '{key=$1" "$9; count[key]++} END {for (k in count) print count[k], k}' apache-access.log | sort -rn

