#!/usr/bin/env bash
#this script uses while case to print numbers from 1 to 20 and text in between
i=1
while [ "$i" -le 20 ]; do
  echo "$i"
  case "$i" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  i=$((i + 1))
done
